FROM python:3.8

# Install Node.js / nodemon
RUN apt-get update && apt-get install -y curl && \
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.4/install.sh | bash && \
    export NVM_DIR="$HOME/.nvm" && \
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && \
    nvm install 16 && \
    nvm alias default 16 && \
    npm install -g nodemon

# ENV PATH="/opt/nodejs/bin:$PATH"

# RUN npm install -g nodemon

# Use non root user
RUN groupadd user && useradd --create-home --home-dir /home/user -g user user

# Configuration
COPY celery/celery-config.cfg /etc/linaro/kernelci-celery.cfg

# Logs folder
RUN mkdir -p /var/www/images/kernel-ci

# Give additional rights on /var/www
RUN chown -R user:user /etc/linaro /var/www

# Copy backend source code and give rigth to user
COPY kernelci-backend /home/user/kernelci-backend
RUN chown -R user:user /home/user/kernelci-backend

# Install python dependencies

RUN pip install -v -r /home/user/kernelci-backend/requirements.txt

# Dedicated entrypoint
COPY celery/entrypoint.sh /srv/entrypoint.sh

# Run application using newly created user
USER user
CMD ["/srv/entrypoint.sh"]
